name: build and push image

on:
  push:
    branches:
      - 'main'
    paths:
      - Dockerfile
      - '.github/workflows/**'

env:
  IMAGE_NAME: "simaofsilva/containerbase-buildpack"
  REPO_URL: "https://github.com/containerbase/buildpack"
  VERSION: "3.17.4" # renovate: datasource=github-tags depName=containerbase/buildpack
  LOCAL_PATH: "/tmp/buildpack"


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clone original repository
        run: |
          git clone ${{ env.REPO_URL }} -b ${{ env.VERSION }} ${{ env.LOCAL_PATH }}

      - name: Check if custom Dockerfile is been used
        run: |
          cp Dockerfile ${{ env.LOCAL_PATH }}
          cat ${{ env.LOCAL_PATH }}/Dockerfile

      - name: Apply fix to dependencies
        run: |
          cp fix-arm64.sh ${{ env.LOCAL_PATH }}
          cd ${{ env.LOCAL_PATH }}
          chmod +x fix-arm64.sh
          ./fix-arm64.sh
          cat src/usr/local/buildpack/tools/docker.sh

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: ${{ env.LOCAL_PATH }}
          platforms: linux/arm64/v8
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest


  delete_old_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.0.2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 15
          keep_minimum_runs: 5
