name: test building image

on:
  push:
    branches-ignore:
      - "main"
    paths:
      - Dockerfile
      - ".github/workflows/**"
      - patch-arm64.sh

env:
  IMAGE_NAME: "simaofsilva/containerbase-buildpack"
  REPO_URL: "https://github.com/containerbase/base"
  VERSION: "9.23.12" # renovate: datasource=github-tags depName=containerbase/base
  LOCAL_PATH: "/tmp/buildpack"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Clone original repository
        run: |
          git clone ${{ env.REPO_URL }} -b ${{ env.VERSION }} ${{ env.LOCAL_PATH }}

      - name: Check if custom Dockerfile is been used
        run: |
          cp Dockerfile ${{ env.LOCAL_PATH }}
          cat ${{ env.LOCAL_PATH }}/Dockerfile

      - name: Patching dependencies
        run: |
          cp patch-arm64.sh ${{ env.LOCAL_PATH }}
          cd ${{ env.LOCAL_PATH }}
          chmod +x patch-arm64.sh
          ./patch-arm64.sh

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.LOCAL_PATH }}
          platforms: linux/arm64/v8
          load: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest
